modLoader="javafml" 
loaderVersion="[32,)"
license="MIT"
[[mods]]
modId="pandoraring"
version="${file.jarVersion}"
displayName="Pandora's Ring"
authors="William Spacefire"
description='''
This is the Pandora's Ring, which allows you to fly..
'''
[[dependencies.angelring]]
   modId="curios"
   mandatory=true
   versionRange="[FORGE-1.16.1-3.0-beta2,]"
   ordering="AFTER"
   side="BOTH"